# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

jobs:
  build:
    docker:
    # specify the version
    - image: circleci/golang:1.9

    working_directory: /go/
    steps:
    - run: sudo apt update && sudo apt install libpcap-dev
    - run: git clone https://github.com/cdstelly/nugget && cd nugget && pwd && env && export GOPATH=/go/nugget && echo $GOPATH
    - run: GOPATH=/go/nugget go get ./...
    # - run: GOPATH=/go/nugget go build github.com/cdstelly/nugget
    - run: GOPATH=/go/nugget go test -v ./...
