# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9

    working_directory: /go/
    steps:
      - run: sudo apt update && sudo apt install libpcap-dev
      - run: git clone https://github.com/cdstelly/nugget && cd nugget && pwd && env && export GOPATH=/go/nugget && echo $GOPATH
      - run: GOPATH=/go/nugget go get ./...
      - run: GOPATH=/go/nugget go test -v github.com/cdstelly/nugget
  build-and-deploy:
    docker:
    # specify the version
      - image: circleci/golang:1.9

    working_directory: /go/
    steps:
      - run: sudo apt update && sudo apt install libpcap-dev
      - run: git clone https://github.com/cdstelly/nugget && cd nugget && pwd && env && export GOPATH=/go/nugget && echo $GOPATH
      - run: GOPATH=/go/nugget go get ./...
      - run: GOPATH=/go/nugget go test -v github.com/cdstelly/nugget
      - run:
        name: Build and push Docker image
        command: |
          wget https://raw.githubusercontent.com/cdstelly/nugget-builder/master/nuggetruntime.conf
          wget https://raw.githubusercontent.com/cdstelly/nugget-builder/master/Dockerfile
          docker build -t cdstelly/nugget:latest .
          echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
          docker push cdstelly/nugget:latest
    
workflows: 
  version: 2
  untagged-build:
    jobs:
      - build
  tagged-build:
    jobs:
      - build-and-deploy: 
          filters: 
            tags: 
              only: /^deploy.*/
