# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9

    working_directory: /go/nugget
    steps:
      - run: sudo apt update && sudo apt install libpcap-dev
      - checkout 
      - run: cd nugget && pwd && env && export GOPATH=/go/nugget && echo $GOPATH
      - run: GOPATH=/go/nugget go get ./...
      - run: GOPATH=/go/nugget go test -v github.com/cdstelly/nugget
  build-and-deploy:
    docker:
    # specify the version
      - image: circleci/golang:1.9

    working_directory: /go/
    steps:
      - add_ssh_keys
      - setup_remote_docker:
          docker_layer_caching: true
      - run: sudo apt update && sudo apt install libpcap-dev
      - checkout 
      - run: cd nugget && pwd && env && export GOPATH=/go/nugget && echo $GOPATH
      - run: GOPATH=/go/nugget go get ./...
      - run: GOPATH=/go/nugget go test -v github.com/cdstelly/nugget
      - run: wget https://raw.githubusercontent.com/cdstelly/nugget-builder/master/nuggetruntime.conf
      - run: wget https://raw.githubusercontent.com/cdstelly/nugget-builder/master/Dockerfile
      - run: docker build -t cdstelly/nugget:latest .
      - run: echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
      - run: docker push cdstelly/nugget:latest
    
workflows: 
  version: 2
  untagged-build:
    jobs:
      - build
  tagged-build:
    jobs:
      - build-and-deploy: 
          filters: 
            tags: 
              only: /^deploy.*/
