// Code generated by protoc-gen-go. DO NOT EDIT.
// source: net-fileinfo.proto

package NTypes

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Net_FileInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Filenames            []string `protobuf:"bytes,2,rep,name=filenames,proto3" json:"filenames,omitempty"`
	Createtime           int64    `protobuf:"varint,3,opt,name=createtime,proto3" json:"createtime,omitempty"`
	Modifytime           int64    `protobuf:"varint,4,opt,name=modifytime,proto3" json:"modifytime,omitempty"`
	Accesstime           int64    `protobuf:"varint,5,opt,name=accesstime,proto3" json:"accesstime,omitempty"`
	Emodifytime          int64    `protobuf:"varint,6,opt,name=emodifytime,proto3" json:"emodifytime,omitempty"`
	Fflags               string   `protobuf:"bytes,7,opt,name=fflags,proto3" json:"fflags,omitempty"`
	Flags                string   `protobuf:"bytes,8,opt,name=flags,proto3" json:"flags,omitempty"`
	Filesize             uint64   `protobuf:"varint,9,opt,name=filesize,proto3" json:"filesize,omitempty"`
	Reconstructeddata    [][]byte `protobuf:"bytes,10,rep,name=reconstructeddata,proto3" json:"reconstructeddata,omitempty"`
	Beenreconstructed    bool     `protobuf:"varint,11,opt,name=beenreconstructed,proto3" json:"beenreconstructed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Net_FileInfo) Reset()         { *m = Net_FileInfo{} }
func (m *Net_FileInfo) String() string { return proto.CompactTextString(m) }
func (*Net_FileInfo) ProtoMessage()    {}
func (*Net_FileInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9aaccb949b068768, []int{0}
}

func (m *Net_FileInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Net_FileInfo.Unmarshal(m, b)
}
func (m *Net_FileInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Net_FileInfo.Marshal(b, m, deterministic)
}
func (m *Net_FileInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Net_FileInfo.Merge(m, src)
}
func (m *Net_FileInfo) XXX_Size() int {
	return xxx_messageInfo_Net_FileInfo.Size(m)
}
func (m *Net_FileInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Net_FileInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Net_FileInfo proto.InternalMessageInfo

func (m *Net_FileInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Net_FileInfo) GetFilenames() []string {
	if m != nil {
		return m.Filenames
	}
	return nil
}

func (m *Net_FileInfo) GetCreatetime() int64 {
	if m != nil {
		return m.Createtime
	}
	return 0
}

func (m *Net_FileInfo) GetModifytime() int64 {
	if m != nil {
		return m.Modifytime
	}
	return 0
}

func (m *Net_FileInfo) GetAccesstime() int64 {
	if m != nil {
		return m.Accesstime
	}
	return 0
}

func (m *Net_FileInfo) GetEmodifytime() int64 {
	if m != nil {
		return m.Emodifytime
	}
	return 0
}

func (m *Net_FileInfo) GetFflags() string {
	if m != nil {
		return m.Fflags
	}
	return ""
}

func (m *Net_FileInfo) GetFlags() string {
	if m != nil {
		return m.Flags
	}
	return ""
}

func (m *Net_FileInfo) GetFilesize() uint64 {
	if m != nil {
		return m.Filesize
	}
	return 0
}

func (m *Net_FileInfo) GetReconstructeddata() [][]byte {
	if m != nil {
		return m.Reconstructeddata
	}
	return nil
}

func (m *Net_FileInfo) GetBeenreconstructed() bool {
	if m != nil {
		return m.Beenreconstructed
	}
	return false
}

type Net_Query struct {
	Querystring          string   `protobuf:"bytes,1,opt,name=querystring,proto3" json:"querystring,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Net_Query) Reset()         { *m = Net_Query{} }
func (m *Net_Query) String() string { return proto.CompactTextString(m) }
func (*Net_Query) ProtoMessage()    {}
func (*Net_Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_9aaccb949b068768, []int{1}
}

func (m *Net_Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Net_Query.Unmarshal(m, b)
}
func (m *Net_Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Net_Query.Marshal(b, m, deterministic)
}
func (m *Net_Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Net_Query.Merge(m, src)
}
func (m *Net_Query) XXX_Size() int {
	return xxx_messageInfo_Net_Query.Size(m)
}
func (m *Net_Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Net_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Net_Query proto.InternalMessageInfo

func (m *Net_Query) GetQuerystring() string {
	if m != nil {
		return m.Querystring
	}
	return ""
}

func init() {
	proto.RegisterType((*Net_FileInfo)(nil), "NTypes.net_FileInfo")
	proto.RegisterType((*Net_Query)(nil), "NTypes.net_Query")
}

func init() { proto.RegisterFile("net-fileinfo.proto", fileDescriptor_9aaccb949b068768) }

var fileDescriptor_9aaccb949b068768 = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xc1, 0x6b, 0xfa, 0x30,
	0x14, 0xc7, 0x49, 0xab, 0xfd, 0xd9, 0xa7, 0xfc, 0x86, 0x41, 0x46, 0x90, 0x31, 0x82, 0xa7, 0x1e,
	0xa6, 0x8c, 0xed, 0xb0, 0xcb, 0xce, 0x1b, 0xbb, 0x0c, 0x56, 0x77, 0x97, 0xd8, 0xbe, 0x4a, 0xc0,
	0xa6, 0x2e, 0x89, 0x03, 0xf7, 0x3f, 0xec, 0xbf, 0xdc, 0x1f, 0x32, 0x92, 0x8a, 0x46, 0x3c, 0xed,
	0xd6, 0xef, 0xe7, 0xf3, 0x12, 0x5e, 0xdf, 0x0b, 0x50, 0x85, 0x76, 0x5a, 0xc9, 0x35, 0x4a, 0x55,
	0x35, 0xb3, 0x8d, 0x6e, 0x6c, 0x43, 0x93, 0xd7, 0xf7, 0xdd, 0x06, 0xcd, 0xe4, 0x27, 0x82, 0x81,
	0x42, 0xbb, 0x78, 0x92, 0x6b, 0x7c, 0x51, 0x55, 0x43, 0xff, 0x43, 0x24, 0x4b, 0x46, 0x38, 0xc9,
	0xd2, 0x3c, 0x92, 0x25, 0xbd, 0x82, 0xd4, 0x1d, 0x55, 0xa2, 0x46, 0xc3, 0x22, 0x1e, 0x67, 0x69,
	0x7e, 0x04, 0xf4, 0x1a, 0xa0, 0xd0, 0x28, 0x2c, 0x5a, 0x59, 0x23, 0x8b, 0x39, 0xc9, 0xe2, 0x3c,
	0x20, 0xce, 0xd7, 0x4d, 0x29, 0xab, 0x9d, 0xf7, 0x9d, 0xd6, 0x1f, 0x89, 0xf3, 0xa2, 0x28, 0xd0,
	0x18, 0xef, 0xbb, 0xad, 0x3f, 0x12, 0xca, 0xa1, 0x8f, 0xc1, 0x05, 0x89, 0x2f, 0x08, 0x11, 0xbd,
	0x84, 0xa4, 0xaa, 0xd6, 0x62, 0x65, 0xd8, 0x3f, 0xdf, 0xf3, 0x3e, 0xd1, 0x11, 0x74, 0x5b, 0xdc,
	0xf3, 0xb8, 0x0d, 0x74, 0x0c, 0x3d, 0xd7, 0xbc, 0x91, 0x5f, 0xc8, 0x52, 0x4e, 0xb2, 0x4e, 0x7e,
	0xc8, 0xf4, 0x06, 0x86, 0x1a, 0x8b, 0x46, 0x19, 0xab, 0xb7, 0x85, 0xc5, 0xb2, 0x14, 0x56, 0x30,
	0xe0, 0x71, 0x36, 0xc8, 0xcf, 0x85, 0xab, 0x5e, 0x22, 0xaa, 0x13, 0xc1, 0xfa, 0x9c, 0x64, 0xbd,
	0xfc, 0x5c, 0x4c, 0xa6, 0x90, 0xba, 0x29, 0xbf, 0x6d, 0x51, 0xef, 0xdc, 0x4f, 0x7d, 0xb8, 0x0f,
	0x63, 0xb5, 0x54, 0xab, 0xfd, 0xac, 0x43, 0x74, 0xf7, 0x4d, 0x60, 0x34, 0x47, 0xfd, 0x29, 0x0b,
	0x5c, 0x9c, 0x6c, 0xe7, 0x01, 0x06, 0xcf, 0x61, 0x1e, 0xce, 0xda, 0x3d, 0xce, 0x0e, 0xb7, 0x8f,
	0x47, 0x21, 0x3a, 0x14, 0x3e, 0xc2, 0xc5, 0xdc, 0x6a, 0x14, 0xf5, 0xdf, 0xcf, 0xde, 0x92, 0x65,
	0xe2, 0x1f, 0xcd, 0xfd, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xef, 0x74, 0xa8, 0x99, 0x4a, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServiceNet_FileInfoClient is the client API for ServiceNet_FileInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceNet_FileInfoClient interface {
	Get_FileInfo(ctx context.Context, in *Net_Query, opts ...grpc.CallOption) (*Net_FileInfo, error)
	Stream_FileInfo(ctx context.Context, in *Net_Query, opts ...grpc.CallOption) (ServiceNet_FileInfo_Stream_FileInfoClient, error)
}

type serviceNet_FileInfoClient struct {
	cc *grpc.ClientConn
}

func NewServiceNet_FileInfoClient(cc *grpc.ClientConn) ServiceNet_FileInfoClient {
	return &serviceNet_FileInfoClient{cc}
}

func (c *serviceNet_FileInfoClient) Get_FileInfo(ctx context.Context, in *Net_Query, opts ...grpc.CallOption) (*Net_FileInfo, error) {
	out := new(Net_FileInfo)
	err := c.cc.Invoke(ctx, "/NTypes.Service_net_FileInfo/Get_FileInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceNet_FileInfoClient) Stream_FileInfo(ctx context.Context, in *Net_Query, opts ...grpc.CallOption) (ServiceNet_FileInfo_Stream_FileInfoClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ServiceNet_FileInfo_serviceDesc.Streams[0], "/NTypes.Service_net_FileInfo/Stream_FileInfo", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceNet_FileInfoStream_FileInfoClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ServiceNet_FileInfo_Stream_FileInfoClient interface {
	Recv() (*Net_FileInfo, error)
	grpc.ClientStream
}

type serviceNet_FileInfoStream_FileInfoClient struct {
	grpc.ClientStream
}

func (x *serviceNet_FileInfoStream_FileInfoClient) Recv() (*Net_FileInfo, error) {
	m := new(Net_FileInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ServiceNet_FileInfoServer is the server API for ServiceNet_FileInfo service.
type ServiceNet_FileInfoServer interface {
	Get_FileInfo(context.Context, *Net_Query) (*Net_FileInfo, error)
	Stream_FileInfo(*Net_Query, ServiceNet_FileInfo_Stream_FileInfoServer) error
}

func RegisterServiceNet_FileInfoServer(s *grpc.Server, srv ServiceNet_FileInfoServer) {
	s.RegisterService(&_ServiceNet_FileInfo_serviceDesc, srv)
}

func _ServiceNet_FileInfo_Get_FileInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Net_Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceNet_FileInfoServer).Get_FileInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NTypes.Service_net_FileInfo/Get_FileInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceNet_FileInfoServer).Get_FileInfo(ctx, req.(*Net_Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceNet_FileInfo_Stream_FileInfo_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Net_Query)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServiceNet_FileInfoServer).Stream_FileInfo(m, &serviceNet_FileInfoStream_FileInfoServer{stream})
}

type ServiceNet_FileInfo_Stream_FileInfoServer interface {
	Send(*Net_FileInfo) error
	grpc.ServerStream
}

type serviceNet_FileInfoStream_FileInfoServer struct {
	grpc.ServerStream
}

func (x *serviceNet_FileInfoStream_FileInfoServer) Send(m *Net_FileInfo) error {
	return x.ServerStream.SendMsg(m)
}

var _ServiceNet_FileInfo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "NTypes.Service_net_FileInfo",
	HandlerType: (*ServiceNet_FileInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get_FileInfo",
			Handler:    _ServiceNet_FileInfo_Get_FileInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream_FileInfo",
			Handler:       _ServiceNet_FileInfo_Stream_FileInfo_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "net-fileinfo.proto",
}
