// Code generated by protoc-gen-go. DO NOT EDIT.
// source: net-fileinfo.proto

package NTypes

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Net_FileInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Filenames            []string `protobuf:"bytes,2,rep,name=filenames,proto3" json:"filenames,omitempty"`
	Createtime           int64    `protobuf:"varint,3,opt,name=createtime,proto3" json:"createtime,omitempty"`
	Modifytime           int64    `protobuf:"varint,4,opt,name=modifytime,proto3" json:"modifytime,omitempty"`
	Accesstime           int64    `protobuf:"varint,5,opt,name=accesstime,proto3" json:"accesstime,omitempty"`
	Emodifytime          int64    `protobuf:"varint,6,opt,name=emodifytime,proto3" json:"emodifytime,omitempty"`
	Fflags               string   `protobuf:"bytes,7,opt,name=fflags,proto3" json:"fflags,omitempty"`
	Flags                string   `protobuf:"bytes,8,opt,name=flags,proto3" json:"flags,omitempty"`
	Filesize             uint64   `protobuf:"varint,9,opt,name=filesize,proto3" json:"filesize,omitempty"`
	Reconstructeddata    [][]byte `protobuf:"bytes,10,rep,name=reconstructeddata,proto3" json:"reconstructeddata,omitempty"`
	Beenreconstructed    bool     `protobuf:"varint,11,opt,name=beenreconstructed,proto3" json:"beenreconstructed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Net_FileInfo) Reset()         { *m = Net_FileInfo{} }
func (m *Net_FileInfo) String() string { return proto.CompactTextString(m) }
func (*Net_FileInfo) ProtoMessage()    {}
func (*Net_FileInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9aaccb949b068768, []int{0}
}

func (m *Net_FileInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Net_FileInfo.Unmarshal(m, b)
}
func (m *Net_FileInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Net_FileInfo.Marshal(b, m, deterministic)
}
func (m *Net_FileInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Net_FileInfo.Merge(m, src)
}
func (m *Net_FileInfo) XXX_Size() int {
	return xxx_messageInfo_Net_FileInfo.Size(m)
}
func (m *Net_FileInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Net_FileInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Net_FileInfo proto.InternalMessageInfo

func (m *Net_FileInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Net_FileInfo) GetFilenames() []string {
	if m != nil {
		return m.Filenames
	}
	return nil
}

func (m *Net_FileInfo) GetCreatetime() int64 {
	if m != nil {
		return m.Createtime
	}
	return 0
}

func (m *Net_FileInfo) GetModifytime() int64 {
	if m != nil {
		return m.Modifytime
	}
	return 0
}

func (m *Net_FileInfo) GetAccesstime() int64 {
	if m != nil {
		return m.Accesstime
	}
	return 0
}

func (m *Net_FileInfo) GetEmodifytime() int64 {
	if m != nil {
		return m.Emodifytime
	}
	return 0
}

func (m *Net_FileInfo) GetFflags() string {
	if m != nil {
		return m.Fflags
	}
	return ""
}

func (m *Net_FileInfo) GetFlags() string {
	if m != nil {
		return m.Flags
	}
	return ""
}

func (m *Net_FileInfo) GetFilesize() uint64 {
	if m != nil {
		return m.Filesize
	}
	return 0
}

func (m *Net_FileInfo) GetReconstructeddata() [][]byte {
	if m != nil {
		return m.Reconstructeddata
	}
	return nil
}

func (m *Net_FileInfo) GetBeenreconstructed() bool {
	if m != nil {
		return m.Beenreconstructed
	}
	return false
}

func init() {
	proto.RegisterType((*Net_FileInfo)(nil), "NTypes.net_FileInfo")
}

func init() { proto.RegisterFile("net-fileinfo.proto", fileDescriptor_9aaccb949b068768) }

var fileDescriptor_9aaccb949b068768 = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x41, 0x4b, 0xf4, 0x30,
	0x10, 0x86, 0x69, 0xbb, 0xdb, 0x6f, 0x3b, 0xbb, 0x7c, 0x68, 0x58, 0x24, 0x2c, 0x22, 0xc1, 0x53,
	0x0e, 0xda, 0x83, 0xde, 0x3d, 0x2a, 0x5e, 0x3c, 0x44, 0xf1, 0xba, 0x64, 0xd3, 0x89, 0x04, 0xda,
	0x64, 0x69, 0xa2, 0xb0, 0xfe, 0x5e, 0x7f, 0x88, 0x34, 0x15, 0xdb, 0xb2, 0x1e, 0xdf, 0xe7, 0x99,
	0x84, 0x61, 0x5e, 0x20, 0x16, 0xc3, 0xb5, 0x36, 0x35, 0x1a, 0xab, 0x5d, 0xb9, 0x6f, 0x5d, 0x70,
	0x24, 0x7f, 0x7a, 0x39, 0xec, 0xd1, 0x5f, 0x7e, 0xa5, 0xb0, 0xb2, 0x18, 0xb6, 0xf7, 0xa6, 0xc6,
	0x47, 0xab, 0x1d, 0xf9, 0x0f, 0xa9, 0xa9, 0x68, 0xc2, 0x12, 0x5e, 0x88, 0xd4, 0x54, 0xe4, 0x1c,
	0x8a, 0xee, 0xa9, 0x95, 0x0d, 0x7a, 0x9a, 0xb2, 0x8c, 0x17, 0x62, 0x00, 0xe4, 0x02, 0x40, 0xb5,
	0x28, 0x03, 0x06, 0xd3, 0x20, 0xcd, 0x58, 0xc2, 0x33, 0x31, 0x22, 0x9d, 0x6f, 0x5c, 0x65, 0xf4,
	0x21, 0xfa, 0x59, 0xef, 0x07, 0xd2, 0x79, 0xa9, 0x14, 0x7a, 0x1f, 0xfd, 0xbc, 0xf7, 0x03, 0x21,
	0x0c, 0x96, 0x38, 0xfa, 0x20, 0x8f, 0x03, 0x63, 0x44, 0xce, 0x20, 0xd7, 0xba, 0x96, 0x6f, 0x9e,
	0xfe, 0x8b, 0x3b, 0xff, 0x24, 0xb2, 0x86, 0x79, 0x8f, 0x17, 0x11, 0xf7, 0x81, 0x6c, 0x60, 0xd1,
	0x2d, 0xef, 0xcd, 0x27, 0xd2, 0x82, 0x25, 0x7c, 0x26, 0x7e, 0x33, 0xb9, 0x82, 0xd3, 0x16, 0x95,
	0xb3, 0x3e, 0xb4, 0xef, 0x2a, 0x60, 0x55, 0xc9, 0x20, 0x29, 0xb0, 0x8c, 0xaf, 0xc4, 0xb1, 0xe8,
	0xa6, 0x77, 0x88, 0x76, 0x22, 0xe8, 0x92, 0x25, 0x7c, 0x21, 0x8e, 0xc5, 0xcd, 0x2b, 0xac, 0x9f,
	0xb1, 0xfd, 0x30, 0x0a, 0xb7, 0x93, 0x6b, 0xdf, 0xc1, 0xc9, 0x03, 0x86, 0x29, 0x5b, 0x97, 0x7d,
	0x37, 0xe5, 0x98, 0x6e, 0xfe, 0xa4, 0xbb, 0x3c, 0xb6, 0x79, 0xfb, 0x1d, 0x00, 0x00, 0xff, 0xff,
	0xa3, 0xe3, 0x08, 0xb1, 0xe3, 0x01, 0x00, 0x00,
}
